name: apod
description: "Astronomy Picture Of the Day."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.3
  dio: ^5.4.3+1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  shimmer: ^3.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  faker: ^2.1.0
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

